# Enable the OpenSSH daemon.
services.openssh.enable = true

[networking]
# Enables wireless support via NetworkManager.
networkmanager.enable = true

# Use StevenBlack's blocklist:
# https://github.com/StevenBlack/hosts
stevenBlackHosts.enable = true

# The global useDHCP flag is deprecated, therefore explicitly set to false here.
# Per-interface useDHCP will be mandatory in the future, so this generated config
# replicates the default behaviour.
useDHCP = false
#interfaces.wlp3s0.useDHCP = true

[services.tailscale]
enable = true
