[nix]
# Use experimental flakes
package = "nixFlakes"
extraOptions = """
  experimental-features = nix-command flakes
"""

# Save space
autoOptimiseStore = true

# Remove need for sudo
trustedUsers = [ "sybrand" ]

[nix.gc]
automatic = true
dates = "monthly"
options = "--delete-older-than 30d"
